#!/bin/sh

export GTK2_RC_FILES=$HOME/.config/gtkrc-2.0
export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd &
urxvtd -q -f -o &
xsetroot -cursor_name left_ptr &
xset -b &
picom &

# if [ "$(xrandr | grep HDMI-1 | awk '{print $2}')" = "connected" ]; then
# 	xrandr --output eDP-1 --auto
# 	xrandr --output HDMI-1 --auto --left-of LVDS1 --primary
# else
# 	xrandr --output eDP-1 --auto --primary
# 	xrandr --output HDMI-1 --off
# fi

sh .fehbg &
# exec bspwm
