#! /bin/sh

#bspc config top_padding 40
bspc config top_padding 35

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config presel_feedback_color \#aa1111

# focused monitor
bspc config focused_border_color \#aa1111

# unfocused monitor
bspc config active_border_color \#aa1111

# unfocused window
# bspc config normal_border_color \#000000

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V

if [ "$(xrandr | grep HDMI1 | awk '{print $2}')" = "connected" ]; then
	bspc monitor HDMI1 -n 0 -d I II III IV V
	bspc monitor LVDS1 -n 1 -d VI VII

	bspc config -m 1 top_padding 0
else
	bspc monitor LVDS1 -n 0 -d I II III IV V
fi

bspc rule -a Gimp state=floating
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

exec xautolock -time 15 -locker 'i3lock-wrapper' &
/home/mark/.panel/panel &
